// src/components/datetoday.vue
<template>
  <div id="datetoday">{{date}}</div>
</template>

<script>
import dayjs from "dayjs";
import timezone from "dayjs/plugin/timezone";
import utc from "dayjs/plugin/utc";
import { reactive, onMounted, toRefs } from "vue";
export default {
  name: "datetoday",
  setup() {
    const today = reactive({ date: "" });

    function todaysdate() {
      dayjs.extend(timezone);
      dayjs.extend(utc);
      today.date = dayjs().tz("Asia/Kathmandu").format("MMMM D, dddd");
      return today.date;
    }

    onMounted(() => setInterval(todaysdate, 1000));
    return { ...toRefs(today) };
  },
};
</script>

// src/components/DateToday.jsx
import React, { useState, useEffect } from 'react';
import dayjs from 'dayjs';
import timezone from 'dayjs/plugin/timezone';
import utc from 'dayjs/plugin/utc';

dayjs.extend(utc);
dayjs.extend(timezone);

const DateToday = () => {
  const [date, setDate] = useState('');

  useEffect(() => {
    const todaysDate = () => {
      setDate(dayjs().tz('Asia/Kathmandu').format('MMMM D, dddd'));
    };

    const intervalId = setInterval(todaysDate, 1000);
    todaysDate(); // Initial call to set the date immediately

    return () => clearInterval(intervalId); // Clean up the interval on component unmount
  }, []);

  return (
    <div id="datetoday">
      {date}
    </div>
  );
};

export default DateToday;
